name = trivia
title = Trivia Mini-Game
description = A fun trivia mini-game mod where players answer questions to win diamond swords
version = 1.0.1
author = justlp566
min_minetest_version = 5.0
depends = default
